# Generated by Django 4.1.7 on 2024-08-01 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='image',
        ),
    ]
